"""initial schema per docs/database-design.md

Revision ID: 13d3056d6d6d
Revises: 
Create Date: 2026-08-24 11:28:05.562261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d3056d6d6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_sets',
    sa.Column('feature_set_version', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code_git_sha', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('feature_set_version')
    )
    op.create_table('heroes',
    sa.Column('hero_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('localized_name', sa.Text(), nullable=False),
    sa.Column('primary_attr', sa.Text(), nullable=True),
    sa.Column('attack_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('hero_id')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ingestion_runs_source_status', 'ingestion_runs', ['source', 'status', 'started_at'], unique=False)
    op.create_table('leagues',
    sa.Column('league_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_index('idx_leagues_tier', 'leagues', ['tier'], unique=False)
    op.create_table('organizations',
    sa.Column('organization_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('patches',
    sa.Column('patch_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('patch_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('account_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('raw_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_responses_content_hash', 'raw_responses', ['content_hash'], unique=False)
    op.create_index('idx_raw_responses_source_endpoint_fetched', 'raw_responses', ['source', 'endpoint', 'fetched_at'], unique=False)
    op.create_table('models',
    sa.Column('model_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('feature_set_version', sa.Text(), nullable=True),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('val_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('val_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_version'], ['feature_sets.feature_set_version'], ),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('name', 'version', name='uq_models_name_version')
    )
    op.create_index('idx_models_is_active', 'models', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('teams',
    sa.Column('team_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('idx_teams_organization_id', 'teams', ['organization_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('radiant_team_id', sa.BigInteger(), nullable=True),
    sa.Column('dire_team_id', sa.BigInteger(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=True),
    sa.Column('patch_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.BigInteger(), nullable=True),
    sa.Column('series_type', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dire_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ),
    sa.ForeignKeyConstraint(['patch_id'], ['patches.patch_id'], ),
    sa.ForeignKeyConstraint(['radiant_team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index('idx_matches_dire_team_id', 'matches', ['dire_team_id'], unique=False)
    op.create_index('idx_matches_league_id', 'matches', ['league_id'], unique=False)
    op.create_index('idx_matches_radiant_team_id', 'matches', ['radiant_team_id'], unique=False)
    op.create_index('idx_matches_start_time', 'matches', ['start_time'], unique=False)
    op.create_table('team_roster_periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_roster_team_account_valid', 'team_roster_periods', ['team_id', 'account_id', 'valid_from'], unique=False)
    op.create_index('idx_roster_valid_range', 'team_roster_periods', ['team_id', 'valid_from', 'valid_to'], unique=False)
    op.create_table('match_features',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_set_version', sa.Text(), nullable=False),
    sa.Column('as_of_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['feature_set_version'], ['feature_sets.feature_set_version'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'team_id', 'feature_set_version')
    )
    op.create_index('idx_match_features_asof', 'match_features', ['as_of_timestamp'], unique=False)
    op.create_table('match_players',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('player_slot', sa.SmallInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('is_radiant', sa.Boolean(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('gold_per_min', sa.Integer(), nullable=True),
    sa.Column('xp_per_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['players.account_id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.hero_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'player_slot')
    )
    op.create_index('idx_match_players_account_id', 'match_players', ['account_id'], unique=False)
    op.create_index('idx_match_players_hero_id', 'match_players', ['hero_id'], unique=False)
    op.create_table('picks_bans',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('ord', sa.SmallInteger(), nullable=False),
    sa.Column('is_pick', sa.Boolean(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('team', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.hero_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'ord')
    )
    op.create_index('idx_picks_bans_hero_id', 'picks_bans', ['hero_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_a_id', sa.BigInteger(), nullable=True),
    sa.Column('team_b_id', sa.BigInteger(), nullable=True),
    sa.Column('team_a_probability', sa.Float(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index('idx_predictions_match_id', 'predictions', ['match_id'], unique=False)
    op.create_index('idx_predictions_predicted_at', 'predictions', ['predicted_at'], unique=False)
    op.create_table('team_ratings',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=False),
    sa.Column('rating_after', sa.Float(), nullable=False),
    sa.Column('k_factor', sa.Float(), nullable=False),
    sa.Column('rating_engine_version', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'match_id')
    )
    op.create_index('idx_team_ratings_team_match', 'team_ratings', ['team_id', 'match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_ratings_team_match', table_name='team_ratings')
    op.drop_table('team_ratings')
    op.drop_index('idx_predictions_predicted_at', table_name='predictions')
    op.drop_index('idx_predictions_match_id', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_picks_bans_hero_id', table_name='picks_bans')
    op.drop_table('picks_bans')
    op.drop_index('idx_match_players_hero_id', table_name='match_players')
    op.drop_index('idx_match_players_account_id', table_name='match_players')
    op.drop_table('match_players')
    op.drop_index('idx_match_features_asof', table_name='match_features')
    op.drop_table('match_features')
    op.drop_index('idx_roster_valid_range', table_name='team_roster_periods')
    op.drop_index('idx_roster_team_account_valid', table_name='team_roster_periods')
    op.drop_table('team_roster_periods')
    op.drop_index('idx_matches_start_time', table_name='matches')
    op.drop_index('idx_matches_radiant_team_id', table_name='matches')
    op.drop_index('idx_matches_league_id', table_name='matches')
    op.drop_index('idx_matches_dire_team_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_teams_organization_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_models_is_active', table_name='models', postgresql_where=sa.text('is_active = true'))
    op.drop_table('models')
    op.drop_index('idx_raw_responses_source_endpoint_fetched', table_name='raw_responses')
    op.drop_index('idx_raw_responses_content_hash', table_name='raw_responses')
    op.drop_table('raw_responses')
    op.drop_table('players')
    op.drop_table('patches')
    op.drop_table('organizations')
    op.drop_index('idx_leagues_tier', table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('idx_ingestion_runs_source_status', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('heroes')
    op.drop_table('feature_sets')
    # ### end Alembic commands ###
