"""phase11: add lane_role to match_players (post-match, historical use only)

Revision ID: 3428dd53fcd0
Revises: 13d3056d6d6d
Create Date: 2026-08-25 16:46:47.441126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3428dd53fcd0'
down_revision: Union[str, Sequence[str], None] = '13d3056d6d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('lane_role', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_players', 'lane_role')
    # ### end Alembic commands ###
